project_id = "zjorcechjdwxmukfzfpe"

[functions.send-email]
verify_jwt = false

[functions.financial-advisor]
verify_jwt = false

[functions.scan-receipt]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.plaid]
verify_jwt = false

[functions.spending-insights]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false